### ISSUE TITLE
BOTW 60 FPS issue

### ISSUE THREAD

**Issue by AJ-Reckless** [theboy181/switch-ptchtxt-mods#20]
I'd like to use the 60FPS mod for BOTW in Yuzu but it doesn't appear to be working.  When I launch the game (after checking that the mod is enabled in properties) I notice no difference.  I'm still locked at 30FPS, and if I unlock my FPS in the emulator and use Nvidia control panel to limit the FPS to 60 the game runs at double speed (as it also does when the mod is disabled).  I know most people use Cemu for BOTW, but my processor is a beast and should be able to handle this game at 60FPS in Yuzu.  Does this require a specific update or DLC to work?

**Comment by AJ-Reckless** [comment]
It seems either missing the update or one of the DLCs was causing this mod not to load.  After installing all available updates and DLC I now have stable 60FPS docked, GPU high, and at 2K resolution in Yuzu.  Thanks for the mod!

**Comment by theboy181** [comment]
good to hear!
