### ISSUE TITLE
Request: Documented recommendations on use of per game resolution mods vs changing yuzu resolution

### ISSUE THREAD

**Issue by mark007** [theboy181/switch-ptchtxt-mods#4]
I love these mods. Now that yuzu has its own resolution upscaling feature, I have a request.

Is it possible to somehow had a note or recommendation for these game mods, either in the downloaded rars, or on the README.md for this repo, or maybe even on the switch mods page [here ](https://github.com/yuzu-emu/yuzu/wiki/Switch-Mods) to indicate which should / should not be used in favor of the yuzu built in resolution scaler.

I have not yet found any concrete recommendations anywhere that says for game x, use the upscaling mod,  set the yuzu upscaler to 1x for that game. For game y, do the opposite for some reason.

Many thanks.

**Comment by theboy181** [comment]
Sorry for the late reply. The EMU scaler will work with my mods, and recommendations for each title is a call the user has to make. 
All my native MODS should be used at 1X imo. 

If there are any significant issues they will always be included int he mods txt file.
