### ISSUE TITLE
Request: Xenoblade Chronicles 2

### ISSUE THREAD

**Issue by AtlasEndurus** [theboy181/switch-ptchtxt-mods#7]
Would you be able to create a proper 60 FPS mod for the game? The existing one speeds up cutscenes and is very substandard. Will happily donate a second time. Thanks for all the great mods!

**Comment by theboy181** [comment]
Check my Discord out. I am working on a Bounty for this game, but I have hit some walls regarding the best solution.
https://linktr.ee/theboy181

**Comment by silverjerk** [comment]
@theboy181 linktree’s Discord link is expired and I’d like to get access to the XC2 60 FPS mod if the bounty is still available. Apologies for reviving an older issue here.
