### ISSUE TITLE
update mods for xb3 update 1.1.1

### ISSUE THREAD

**Issue by reloxx13** [theboy181/switch-ptchtxt-mods#9]

**Comment by ayurai** [comment]
please \o/

**Comment by theboy181** [comment]
There is no reason to update for this version.

**Comment by ayurai** [comment]
I could use the same argument, there is no reason to not go to this version if not from this mod itself.. it is your call, of course, is your mod after all. But any update that only fix things and dont breaks nothing, is indisputably better than previous version
